const movies = [
  { title: "The Brutalist", year: 2024, director: "Brady Corbet", poster: "images/posters/the-brutalist.jpg" },
  { title: "One Battle After Another", year: 2025, director: "Paul Thomas Anderson", poster: "images/posters/one-battle-after-another.jpg" },
  { title: "Dune: Part One", year: 2021, director: "Denis Villeneuve", poster: "images/posters/dune-part-one.jpg" },
  { title: "Dune: Part Two", year: 2024, director: "Denis Villeneuve", poster: "images/posters/dune-part-two.jpg" },
  { title: "Eddington", year: 2025, director: "Ari Aster", poster: "images/posters/eddington.jpg" },
  { title: "The Holdovers", year: 2023, director: "Alexander Payne", poster: "images/posters/the-holdovers.jpg" },
  { title: "Materialists", year: 2025, director: "Celine Song", poster: "images/posters/materialists.jpg" },
  { title: "Sinners", year: 2025, director: "Ryan Coogler", poster: "images/posters/sinners.jpg" },
  { title: "Oppenheimer", year: 2023, director: "Christopher Nolan", poster: "images/posters/oppenheimer.jpg" },
  { title: "Interstellar", year: 2014, director: "Christopher Nolan", poster: "images/posters/interstellar.jpg" },
  { title: "Dunkirk", year: 2017, director: "Christopher Nolan", poster: "images/posters/dunkirk.jpg" },
  { title: "Catch Me If You Can", year: 2002, director: "Steven Spielberg", poster: "images/posters/catch-me-if-you-can.jpg" },
  { title: "Saving Private Ryan", year: 1998, director: "Steven Spielberg", poster: "images/posters/saving-private-ryan.jpg" },
  { title: "The Godfather", year: 1972, director: "Francis Ford Coppola", poster: "images/posters/the-godfather.jpg" },
  { title: "The Godfather Part II", year: 1974, director: "Francis Ford Coppola", poster: "images/posters/the-godfather-part-ii.jpg" },
  { title: "The Godfather Part III", year: 1990, director: "Francis Ford Coppola", poster: "images/posters/the-godfather-part-iii.jpg" },
  { title: "Django Unchained", year: 2012, director: "Quentin Tarantino", poster: "images/posters/django-unchained.jpg" },
  { title: "Pulp Fiction", year: 1994, director: "Quentin Tarantino", poster: "images/posters/pulp-fiction.jpg" },
  { title: "Kill Bill: Vol. 1", year: 2003, director: "Quentin Tarantino", poster: "images/posters/kill-bill-vol-1.jpg" },
  { title: "Kill Bill: Vol. 2", year: 2004, director: "Quentin Tarantino", poster: "images/posters/kill-bill-vol-2.jpg" },
  { title: "The Killer", year: 2023, director: "David Fincher", poster: "images/posters/the-killer.jpg" },
  { title: "Once Upon a Time in Hollywood", year: 2019, director: "Quentin Tarantino", poster: "images/posters/once-upon-a-time-in-hollywood.jpg" },
  { title: "Casino", year: 1995, director: "Martin Scorsese", poster: "images/posters/casino.jpg" },
  { title: "Inglourious Basterds", year: 2009, director: "Quentin Tarantino", poster: "images/posters/inglourious-basterds.jpg" },
  { title: "The Hateful Eight", year: 2015, director: "Quentin Tarantino", poster: "images/posters/the-hateful-eight.jpg" },
  { title: "Jackie Brown", year: 1997, director: "Quentin Tarantino", poster: "images/posters/jackie-brown.jpg" },
  { title: "The Martian", year: 2015, director: "Ridley Scott", poster: "images/posters/the-martian.jpg" },
  { title: "Anora", year: 2024, director: "Sean Baker", poster: "images/posters/anora.jpg" },
  { title: "The Florida Project", year: 2017, director: "Sean Baker", poster: "images/posters/the-florida-project.jpg" },
  { title: "Red Rocket", year: 2021, director: "Sean Baker", poster: "images/posters/red-rocket.jpg" },
  { title: "The Substance", year: 2024, director: "Coralie Fargeat", poster: "images/posters/the-substance.jpg" },
  { title: "Blow Out", year: 1981, director: "Brian De Palma", poster: "images/posters/blow-out.jpg" },
  { title: "Taxi Driver", year: 1976, director: "Martin Scorsese", poster: "images/posters/taxi-driver.jpg" },
  { title: "The Conversation", year: 1974, director: "Francis Ford Coppola", poster: "images/posters/the-conversation.jpg" },
  { title: "Vertigo", year: 1958, director: "Alfred Hitchcock", poster: "images/posters/vertigo.jpg" },
  { title: "The Matrix", year: 1999, director: "Lana Wachowski; Lilly Wachowski", poster: "images/posters/the-matrix.jpg" },
  { title: "Margin Call", year: 2011, director: "J. C. Chandor", poster: "images/posters/margin-call.jpg" },
  { title: "All the Money in the World", year: 2017, director: "Ridley Scott", poster: "images/posters/all-the-money-in-the-world.jpg" },
];
